### ISSUE TITLE
disney park selection

### ISSUE THREAD

**Issue by jessdorrien** [ChrisMunozCodes/Sunshine-Attractions#49]
when you select a park other than magic kingom it gives you this
<img width="644" alt="Screen Shot 2023-09-22 at 10 41 16 PM" src="https://github.com/ChrisMunozCodes/Sunshine-Attractions/assets/145820553/f4ed5b05-791e-4df5-a98d-e698f613a510">

**Comment by ChrisMunozCodes** [comment]
This issue should be resolved now.

Thanks!
