### ISSUE TITLE
when you pick a restaurant (the wait time thing)

### ISSUE THREAD

**Issue by jessdorrien** [ChrisMunozCodes/Sunshine-Attractions#50]
<img width="757" alt="Screen Shot 2023-09-22 at 10 42 54 PM" src="https://github.com/ChrisMunozCodes/Sunshine-Attractions/assets/145820553/11a80c3d-a54f-4ed5-9b19-89c4211601b7">

**Comment by ChrisMunozCodes** [comment]
This issue is now resolved.

Thanks!
