### ISSUE TITLE
comments you posted

### ISSUE THREAD

**Issue by jessdorrien** [ChrisMunozCodes/Sunshine-Attractions#51]
it shows other peoples comments in the comments you posted 

<img width="1061" alt="Screen Shot 2023-09-22 at 10 45 56 PM" src="https://github.com/ChrisMunozCodes/Sunshine-Attractions/assets/145820553/ffcd1e91-a59a-4b1d-81b8-e3a00dcd8f31">

**Comment by ChrisMunozCodes** [comment]
This issue should be resolved now.

Thanks!
