### ISSUE TITLE
weird apostrophe in the header

### ISSUE THREAD

**Issue by jessdorrien** [ChrisMunozCodes/Sunshine-Attractions#56]
<img width="363" alt="Screen Shot 2023-09-24 at 6 36 34 PM" src="https://github.com/ChrisMunozCodes/Sunshine-Attractions/assets/145820553/4f263326-5c73-46f0-b631-2a6511240e8d">

**Comment by ChrisMunozCodes** [comment]
Good catch!

I got this issue resolved.
Thanks!
